# Define stages for your pipeline
stages:
  - install-dependencies
  - build
  - test
  - dockerize
  - deploy

# Define global variables (optional)
variables:
  FRONTEND_IMAGE: registry.gitlab.com/<your-namespace>/<project-name>/frontend
  BACKEND_IMAGE: registry.gitlab.com/<your-namespace>/<project-name>/backend
  DOCKER_DRIVER: overlay2  # Needed for Docker-in-Docker

# Frontend job: Install dependencies and build React app
frontend-job:
  stage: install-dependencies
  image: node:14-alpine
  script:
    - echo "Installing dependencies for frontend..."
    - cd frontend
    - npm install
    - echo "Building the React app..."
    - npm run build
  artifacts:
    paths:
      - frontend/build/  # Save the built React app for later jobs
  only:
    - main

# Backend job: Install dependencies and test Flask API
backend-job:
  stage: test
  image: python:3.9-slim
  script:
    - echo "Installing dependencies for backend..."
    - cd backend
    - pip install -r requirements.txt
    - echo "Running backend tests..."
    - pytest
  only:
    - main

# Build Docker images for frontend and backend
docker-build:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker images..."
    - docker build -t $FRONTEND_IMAGE:latest ./frontend
    - docker build -t $BACKEND_IMAGE:latest ./backend
    - if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        echo "Pushing images to Docker registry...";
        echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY;
        docker push $FRONTEND_IMAGE:latest;
        docker push $BACKEND_IMAGE:latest;
      fi
  only:
    - main

# OPTIONAL: Deployment job
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Add your deployment steps here (e.g., SSH into server and deploy images)
  only:
    - tags